output

diff --git a/usr/share/gpg-bash-lib/unit-tests/traps_and_shopts b/usr/share/gpg-bash-lib/unit-tests/traps_and_shopts
--- a/usr/share/gpg-bash-lib/unit-tests/traps_and_shopts
+++ b/usr/share/gpg-bash-lib/unit-tests/traps_and_shopts
@@ -6,7 +6,7 @@
 ## {{{ setup
 
 gpg_bash_lib_function_unit_test_error_handler() {
-   echo "$FUNCNAME ERROR!" >&2
+   echo "$FUNCNAME ERROR #0 !" >&2
    exit 1
 }
 
